---
title: "EPL Prediction"
author: "JFlynn"
date: "1/3/2019"
output: html_document
---


```{r, echo = FALSE, warning = FALSE, message = FALSE}

# devtools::install_github("torvaney/footballdatr")
# devtools::install_github("torvaney/regista")

library(tidyverse)
library(scales)
library(lubridate)
library(regista)

data <- footballdatr::fetch_data(
        "england", division = 0, season = 2018) %>% 
        factor_teams(c("home", "away"))

glimpse(data)


```

## Work out the unplayed games

```{r, echo = FALSE, warning = FALSE, message = FALSE}

teams <- factor(levels(data$home), levels = levels(data$home))

unplayed_games <- teams %>%
        crossing(home = teams, 
                           away = teams) %>% 
        filter(home != away) %>% 
        anti_join(data, by = c("home", "away"))

unplayed_games

model <- dixoncoles(hgoal, agoal, home, away, data = data)

model


```


```{r}

team_parameters <- broom::tidy(model) %>% 
        filter(parameter %in% c("off", "def")) %>% 
        mutate(value = exp(value)) %>% 
        spread(parameter, value)

team_parameters %>% 
        ggplot(aes(x = (-1 * def), y = off)) + 
        geom_point(alpha = 0.5) + 
        ggrepel::geom_text_repel(aes(label = team)) + 
        theme_minimal() + 
        labs(title = "Team strength estimates", 
             y = "Attack", 
             x = "Defence") +
#        scale_x_continuous(limits = c(0, NA)) +
        scale_y_continuous(limits = c(0, NA))


```



```{r}

match_probabilities <- broom::augment(
        model, unplayed_games, type.predict = "outcomes") %>% 
        unnest() %>% 
        spread(outcome, prob) %>%
        select(-.)

match_probabilities

unplayed_scorelines <- broom::augment(
        model, unplayed_games, 
        type.predict = "scorelines") %>% 
        unnest() %>%
        select(-.)

unplayed_scorelines

planning <- unplayed_scorelines %>%
        left_join(data %>% 
                          select(home, away, date))

data %>% 
        select(home, away, date) %>%
        filter(home == 'Man United' & 
                       away == 'Watford')

```

```{r}


played_scorelines <- data %>% 
        select(home, away, hgoal, agoal) %>% 
        mutate(prob = 1.0)

scorelines <- bind_rows( 
        played_scorelines, 
        unplayed_scorelines)

scorelines

```


```{r}

simulate_season <- function(scoreline_probabilities) { 
        scoreline_probabilities %>% 
                nest(hgoal, agoal, prob, .key = "scorelines") %>% 
                mutate(sampled = map(
                        scorelines, ~ sample_n(., 1, weight = prob))) %>% 
                select(-scorelines) %>% 
                unnest()
}

# Show 1 simulation as an example
single_simulation <- simulate_season(scorelines)
sample_n(single_simulation, 5)


```



```{r}

calculate_table <- function(games) { 
        
        games_augmented <- games %>% 
                mutate(hpoints = case_when(
                        hgoal > agoal  ~ 3,
                        hgoal == agoal ~ 1,
                        agoal > hgoal  ~ 0),
                       apoints = case_when(
                        hgoal > agoal  ~ 0, 
                        hgoal == agoal ~ 1, 
                        agoal > hgoal  ~ 3))
        
        games_home <- games_augmented %>% 
                select(
                        team = home,
                        gf = hgoal, 
                        ga = agoal, 
                        points = hpoints) 
        
        games_away <- games_augmented %>% 
                select(
                        team = away, 
                        gf = agoal, 
                        ga = hgoal, 
                        points = apoints)
        
        bind_rows(games_home, games_away) %>% 
                group_by(team) %>% 
                summarise(w = sum(gf > ga), 
                          d = sum(gf == ga),
                          l  = sum(gf < ga),
                          gf = sum(gf),
                          ga = sum(ga),
                          gd = gf - ga,
                          points = sum(points)) %>%
                arrange(desc(points), desc(gd), desc(gf)) %>%
                mutate(position = row_number())
}


```


```{r}

calculate_table(data)

```


```{r}

n_simulations <- 1000

simulated_tables <-
  rerun(n_simulations, simulate_season(scorelines)) %>%
  map(calculate_table) %>%
  bind_rows(.id = "simulation_id")

simulated_tables

```




```{r}

simulated_tables %>%
  count(team, points) %>%
  ggplot(aes(x = points, y = reorder(team, points))) +
  geom_tile(aes(alpha = n / n_simulations),
            fill = plot_colour) +
  scale_alpha_continuous(range = c(0, 1)) +
  labs(title = "Points total probabilities",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(legend.position = "none")

```

