---
title: "Sage Work"
author: "JFlynn"
date: "8/26/2018"
output: html_document
---

```{r, echo = FALSE, warning = FALSE, message= FALSE}

library(tidyverse)
library(scales)
library(lubridate)
library(newswhipstyle)

sage <- read_csv("~/Downloads/report1537699758392.csv")
#client <- read_csv("~/Downloads/report1537699758392.csv")

sage <- sage %>%
        mutate(date_opened = as.Date(`Date Opened`, format = '%d/%m/%Y'),
               quarter = floor_date(date_opened, unit = 'quarter')) %>%
        filter(!is.na(quarter)) %>%
        rename(status = `CMG Case Review`)

sage$quarter_for_idiots = 0
sage$quarter_for_idiots[sage$quarter == "2017-01-01"] <- 'Q1 2017'
sage$quarter_for_idiots[sage$quarter == "2017-04-01"] <- 'Q2 2017'
sage$quarter_for_idiots[sage$quarter == "2017-07-01"] <- 'Q3 2017'
sage$quarter_for_idiots[sage$quarter == "2017-10-01"] <- 'Q4 2017'
sage$quarter_for_idiots[sage$quarter == "2018-01-01"] <- 'Q1 2018'
sage$quarter_for_idiots[sage$quarter == "2018-04-01"] <- 'Q2 2018'
sage$quarter_for_idiots[sage$quarter == "2018-07-01"] <- 'Q3 2018'
sage$quarter_for_idiots[sage$quarter == "2018-07-01"] <- 'Q3 2018'

sage <- sage %>%
        mutate(quarter_for_idiots = factor(quarter_for_idiots, 
                   levels = c('Q1 2017', 'Q2 2017', 'Q3 2017', 
                                'Q4 2017', 'Q1 2018', 'Q2 2018',
                              'Q3 2018')),
               status = factor(status,
                               levels = c('Green', 'Amber', 'Red')))

stat <- sage %>%
        group_by(quarter, quarter_for_idiots, Area, status) %>%
        summarise(count = n()) %>%
        filter(!is.na(Area))

```


## {.tabset .tabset-pills}

### No. of Case By Area, By Quarter, Rating

```{r, echo = FALSE, warning = FALSE, message= FALSE}


sage %>%
        group_by(quarter, quarter_for_idiots, Area) %>%
        summarise(count = n()) %>%
        filter(!is.na(Area)) %>%
        ggplot(aes(quarter_for_idiots, count, color = Area, group = Area)) +
        geom_line(size = 1.1) +
        theme_newswhip(theme = 'dark') +
        scale_y_continuous(labels = c(10, 20, 30, 40, 50),
                           breaks = c(10, 20, 30, 40, 50)) +
        scale_color_newswhip(palette = 'colorful_light') +
        labs(title = 'Total Cases Per Area',
             x = '', y = 'Number of Cases',
             fill = 'Area')


sage %>%
        group_by(quarter, quarter_for_idiots, Area) %>%
        summarise(count = n()) %>%
        filter(!is.na(Area)) %>%
        ggplot(aes(quarter_for_idiots, Area, fill = count)) +
        geom_tile(color = '#FFFFFF') +
        theme_newswhip() +
        scale_fill_newswhip(discrete = FALSE, 
                            reverse = TRUE, 
                            palette = 'primary') +
        labs(title = 'Total Cases Per Area',
             x = '', y = 'Number of Cases',
             fill = 'Area')

stat_plot <- function(data, x) {
        data %>%
        filter(Area == x) %>%
        ggplot(aes(quarter_for_idiots, count, color = status,
                   group = status)) +
        geom_point(size = 3, alpha = .8) +
        geom_line(size = 1.5, alpha = .8) +
        theme_newswhip() +
        scale_color_manual(values = c(
                '#139717', '#ffbf00', '#ff0000'
        )) +
        labs(title = paste0('Case Status',
                            '\nArea: ', x),
             y = 'Number of Cases', x = '',
             color = 'Status') +
        scale_y_continuous(limits = c(0, 40))
}

stat_plot(stat, "Cork & Kerry")
stat_plot(stat, "Dublin North")
stat_plot(stat, "Dublin SE & Wicklow")
stat_plot(stat, "Dublin South West & Kildare")
stat_plot(stat, "Galway & Mayo")
stat_plot(stat, "Laois, Offaly & Westmeath")
stat_plot(stat, "Mid West")
stat_plot(stat, "North East")
stat_plot(stat, "North West")
stat_plot(stat, "South East")
stat_plot(stat, "South East Project")



sage %>%
        rename(hpi = `High Priority Issue`) %>%
        group_by(quarter, hpi) %>%
        summarise(count = n()) %>%
        filter(!is.na(hpi)) %>%
        ggplot(aes(quarter, hpi, fill = count)) +
        geom_tile(color = '#FFFFFF') +
        theme_newswhip() +
        scale_fill_newswhip(discrete = FALSE, 
                            reverse = TRUE, 
                            palette = 'secondary') +
        labs(title = 'High Priority Issues Per Quarter',
             x = '', y = 'Number of Cases',
             fill = 'Priority Issues')


```





```{r, echo = FALSE, warning = FALSE, message= FALSE, fig.width=8}


clients_c <- client %>%
        mutate(created = as.Date(`Created Date`, format = '%d/%m/%Y'),
               quarter = floor_date(created, unit = 'quarter')) %>%
        group_by(Area, quarter) %>%
        summarise(clients = n_distinct(`Contact ID`)) %>%
        filter(!is.na(Area))

clients_c$quarter_for_idiots = 0
clients_c$quarter_for_idiots[
        clients_c$quarter == "2017-01-01"] <- 'Q1 2017'
clients_c$quarter_for_idiots[
        clients_c$quarter == "2017-04-01"] <- 'Q2 2017'
clients_c$quarter_for_idiots[
        clients_c$quarter == "2017-07-01"] <- 'Q3 2017'
clients_c$quarter_for_idiots[
        clients_c$quarter == "2017-10-01"] <- 'Q4 2017'
clients_c$quarter_for_idiots[
        clients_c$quarter == "2018-01-01"] <- 'Q1 2018'
clients_c$quarter_for_idiots[
        clients_c$quarter == "2018-04-01"] <- 'Q2 2018'
clients_c$quarter_for_idiots[
        clients_c$quarter == "2018-07-01"] <- 'Q3 2018'

clients_c <- clients_c %>%
        mutate(quarter_for_idiots = factor(quarter_for_idiots, 
                   levels = c('Q1 2017', 'Q2 2017', 'Q3 2017', 
                                'Q4 2017', 'Q1 2018', 'Q2 2018',
                              'Q3 2018')))

clients_c <- client %>%
        rename('location' = `Where is the client?`) %>%
        mutate(created = as.Date(`Created Date`, format = '%d/%m/%Y'),
               quarter = floor_date(created, unit = 'quarter')) %>%
        group_by(location, quarter) %>%
        summarise(clients = n_distinct(`Contact ID`)) %>%
        filter(!is.na(location))

clients_c$quarter_fi = 0
clients_c$quarter_fi[clients_c$quarter == "2017-01-01"] <- 'Q1 2017'
clients_c$quarter_fi[clients_c$quarter == "2017-04-01"] <- 'Q2 2017'
clients_c$quarter_fi[clients_c$quarter == "2017-07-01"] <- 'Q3 2017'
clients_c$quarter_fi[clients_c$quarter == "2017-10-01"] <- 'Q4 2017'
clients_c$quarter_fi[clients_c$quarter == "2018-01-01"] <- 'Q1 2018'
clients_c$quarter_fi[clients_c$quarter == "2018-04-01"] <- 'Q2 2018'
clients_c$quarter_fi[clients_c$quarter == "2018-07-01"] <- 'Q3 2018'

clients_c <- clients_c %>%
        mutate(quarter_fi = factor(quarter_fi, 
                   levels = c('Q1 2017', 'Q2 2017', 'Q3 2017', 
                                'Q4 2017', 'Q1 2018', 'Q2 2018',
                              'Q3 2018')))

clients_c %>%
        ggplot(aes(quarter_fi, clients, color = location,
                   group = location)) +
        geom_point(size = 3, alpha = .6) +
        geom_line(size = 1.5, alpha = .6) +
        theme_newswhip() +
        labs(title = 'Where Are Sage Clients Based?',
             x = '', y = 'Clients',
             color = '') +
        scale_color_newswhip(palette = 'colorful_light')

```

### Total Opened Cases 

Total number of OPENED cases by case rating (red, amber, green) from jan 1 2017 - today

```{r, echo = FALSE, warning = FALSE, message= FALSE, fig.width=8}


min <- min(sage$date_opened)
max <- max(sage$date_opened)

dat <- sage %>%
        group_by(quarter, status, quarter_for_idiots) %>%
        summarise(count = n()) %>%
        ungroup()

dat2 <- sage %>%
        group_by(quarter, quarter_for_idiots) %>%
        summarise(count = n()) %>%
        ungroup() %>% 
        mutate(status = 'Total')

rbind(dat, dat2) %>%
        ggplot(aes(quarter_for_idiots, count, color = status,
                   group = status)) +
        geom_point(size = 3, alpha = .6) +
        geom_line(size = 1.5, alpha = .6) + 
        theme_newswhip() +
        scale_color_manual(values = c(
                '#139717', '#ffbf00', '#ff0000', '#4faeba'
        )) +
        labs(title = 'Red Amber Green and Total Cases Nationally',
             subtitle = paste0('Date Range ', min, ' - ', max),
             y = 'Number of Cases', x = '',
             color = 'Status')
        

```


### Total Number of Active Clients

Total number of active clients, from jan 1 2017 - today

```{r, echo = FALSE, warning = FALSE, message = FALSE, fig.width = 8}

clients_c_2  <- client %>%
        mutate(created = as.Date(`Created Date`, format = '%d/%m/%Y'),
               quarter = floor_date(created, unit = 'quarter')) %>%
        filter(!is.na(created))

clients_c_2$quarter2 = 0
clients_c_2$quarter2[clients_c_2$quarter == "2017-01-01"] <- 'Q1 2017'
clients_c_2$quarter2[clients_c_2$quarter == "2017-04-01"] <- 'Q2 2017'
clients_c_2$quarter2[clients_c_2$quarter == "2017-07-01"] <- 'Q3 2017'
clients_c_2$quarter2[clients_c_2$quarter == "2017-10-01"] <- 'Q4 2017'
clients_c_2$quarter2[clients_c_2$quarter == "2018-01-01"] <- 'Q1 2018'
clients_c_2$quarter2[clients_c_2$quarter == "2018-04-01"] <- 'Q2 2018'
clients_c_2$quarter2[clients_c_2$quarter == "2018-07-01"] <- 'Q3 2018'

clients_c_2 <- clients_c_2 %>%
        mutate(quarter2 = factor(quarter2, 
                   levels = c('Q1 2017', 'Q2 2017', 'Q3 2017', 
                                'Q4 2017', 'Q1 2018', 'Q2 2018',
                              'Q3 2018')))

min <- min(clients_c_2$created)
max <- max(clients_c_2$created)

clients_c_2 %>%
        group_by(quarter, quarter2) %>%
        summarise(clients = n_distinct(`Contact ID`)) %>% 
        ggplot(aes(quarter2, clients, group = 1)) +
        geom_col(fill = '#4faeba', color = '#FFFFFF') + 
        theme_newswhip() +
        labs(title = 'Number of New Clients By Quarter',
             subtitle = paste0('Date Range ', min, ' - ', max),
             y = 'Number of Cases', x = '')
        


```


### Comparison Q3 2018 to Q3 2017

```{r, echo = FALSE, warning = FALSE, message = FALSE, fig.width = 8}


## Cases 2017 - 2018
sage %>%
        filter(quarter == '2017-07-01' |
                       quarter == '2018-07-01' ) %>% 
        group_by(quarter, quarter_for_idiots) %>%
        summarise(cases = n_distinct(`Support & Advocacy Cases: Support & Advocacy Cases Ref`)) %>%
        ggplot(aes(quarter_for_idiots, cases, fill = quarter_for_idiots)) +
        geom_col(color = '#FFFFFF') +
        theme_newswhip() +
        scale_fill_newswhip(palette = 'colorful_light') +
        guides(color = FALSE) +
        labs(title = '2017 to 2018 Q3 Comparison \nNumber of Cases',
             subtitle = 'At time of generation, 2018 Quarter 3 \nData was incomplete', 
             x = '', y = 'Cases', fill = '')
        
        
sage %>%
        filter(quarter == '2017-07-01' |
                       quarter == '2018-07-01' ) %>% 
        group_by(quarter, quarter_for_idiots, Area) %>%
        summarise(cases = 
          n_distinct(`Support & Advocacy Cases: Support & Advocacy Cases Ref`)) %>%
        ggplot(aes(Area, cases, fill = fct_relevel(quarter_for_idiots, 'Q3 2018'))) +
        geom_col(color = '#FFFFFF', position = 'dodge') +
        theme_newswhip() +
        scale_fill_newswhip(palette = 'colorful_light') +
        guides(color = FALSE) +
        labs(title = '2017 to 2018 Q3 Comparison \nNumber of Cases',
             subtitle = 'At time of generation, 2018 Quarter 3 \nData was incomplete', 
             x = '', y = 'Cases', fill = '') +
        coord_flip()




## Clients 2017 - 2018
clients_c_2 %>%
        filter(quarter == '2017-07-01' |
                       quarter == '2018-07-01') %>%
        group_by(quarter, quarter2) %>%
        summarise(clients = n_distinct(`Contact ID`)) %>%
        ggplot(aes(quarter2, clients, 
                   fill = quarter2)) +
        geom_col() +
        theme_newswhip() +
        scale_fill_newswhip(palette = 'colorful_light') +
        guides(color = FALSE)  +
        labs(title = '2017 to 2018 Q3 Comparison \nNumber of Clients',
             subtitle = 'At time of generation, 2018 Q3 \nData was incomplete', x = '', y = 'Clients')


clients_c_2 <- clients_c_2 %>%
        mutate(quarter2 = factor(quarter2, 
                   levels = c('Q1 2017', 'Q2 2017', 'Q3 2017', 
                                'Q4 2017', 'Q1 2018', 'Q2 2018',
                              'Q3 2018')))

clients_c_2 %>%
        filter(quarter == '2017-07-01' |
                       quarter == '2018-07-01') %>%
        group_by(quarter, quarter2, Area) %>%
        summarise(clients = n_distinct(`Contact ID`)) %>%
        ggplot(aes(Area, clients, 
                   fill = fct_relevel(quarter2, 'Q3 2018'))) +
        geom_col(position = 'dodge') +
        theme_newswhip() +
        scale_fill_newswhip(palette = 'colorful_light') +
        labs(title = '2017 to 2018 Q3 Comparison \nNumber of Clients',
             subtitle = 'At time of generation, 2018 Q3 \nData was incomplete', 
             x = '', y = 'Clients', fill = '') +
        coord_flip()



```




